grid_map_topic: /grid_map
grid_map_visualizations:
  - name: obstacles
    type: occupancy_grid
    params:
      layer: obstacles
      data_min: 0.0
      data_max: 1.0
  - name: leo
    type: occupancy_grid
    params:
      layer: leo
      data_min: 0.0
      data_max: 1.0